#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : lm-sensors
Version  : 3.5.0
Release  : 1
URL      : https://github.com/lm-sensors/lm-sensors/archive/V3-5-0.tar.gz
Source0  : https://github.com/lm-sensors/lm-sensors/archive/V3-5-0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: lm-sensors-license = %{version}-%{release}
BuildRequires : bison
BuildRequires : flex

%description
OVERVIEW OF THE LM-SENSORS PACKAGE
==================================
The lm-sensors package, version 3, provides user-space support for the
hardware monitoring drivers in Linux 2.6.5 and later. For older kernel
versions, you have to use lm-sensors version 2.

%package license
Summary: license components for the lm-sensors package.
Group: Default

%description license
license components for the lm-sensors package.


%prep
%setup -q -n lm-sensors-3-5-0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1546267094
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1546267094
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/lm-sensors
cp COPYING %{buildroot}/usr/share/package-licenses/lm-sensors/COPYING
cp COPYING.LGPL %{buildroot}/usr/share/package-licenses/lm-sensors/COPYING.LGPL
%make_install

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/lm-sensors/COPYING
/usr/share/package-licenses/lm-sensors/COPYING.LGPL
